# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ WINDOW & LAYER RULES
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

layerrule {
    name = "lr1"
    match:namespace = ^(volume_osd)$
    no_anim = on
}

layerrule {
    name = "lr2"
    match:namespace = ^(brightness_osd)$
    no_anim = on
}

layerrule {
    name = "lr3"
    match:namespace = hyprpicker
    no_anim = on
}

layerrule {
    name = "lr4"
    match:namespace = qsdock
    no_anim = on
}

layerrule {
    name = "lr5"
    match:namespace = ext-session-lock
    blur = on
    ignore_alpha = 0.2
}

# ─────────────────────────────
# Window rules
# ─────────────────────────────

# ───────── App Launcher ─────────
windowrule {
    name = "app_launcher"
    match:title = ^(app-launcher)$
    float = on
    center = on
    size = 1200 600
    animation = slide
}

# ───────── MASTER QUICKSHELL CONTAINER ─────────
windowrule {
    name = "master_rule"
    match:title = ^(qs-master)$
    float = on
    no_shadow = on
    no_initial_focus = on
}
