foreground   #f7f1ff
background   #0b0b0b
cursor       #f7f1ff

# Black
color0       #0b0b0b
color8       #2a2a2a

# Red
color1       #fc618d
color9       #fc618d

# Green
color2       #7bd88f
color10      #7bd88f

# Yellow
color3       #fce566
color11      #fce566

# Blue
color4       #fd9353
color12      #fd9353

# Magenta
color5       #948ae3
color13      #948ae3

# Cyan
color6       #5ad4e6
color14      #5ad4e6

# White
color7       #f7f1ff
color15      #f7f1ff

# Cursor
cursor #f7f1ff
cursor_text_color #0b0b0b

# Selection highlight
selection_foreground none
selection_background #2a2a2a
